### ISSUE TITLE
This project still maintained?

### ISSUE THREAD

**Issue by splittingred** [collectiveidea/interactor#104]
We're considering forking, as there aren't any commits to master since May 13. Is there still active development/maintenance on canonical, or should we go ahead and fork?

**Comment by gregory** [comment]
Hey  @danielmorrison @laserlemon do you have any idea if this project is still maintained? 
Do you guys need maintainers?

**Comment by laserlemon** [comment]
@splittingred, @gregory: Thank you for reaching out. Interactor is still maintained although we have finite time to dedicate to its ongoing maintenance. In reality, it comes in waves. There is some internal momentum in the design for version 4. That said, there's nothing wrong with forking if the current state isn't meeting your needs. Please feel free and we'll be interested to see what changes are made!
