### ISSUE TITLE
Question: solid_use_case comparison

### ISSUE THREAD

**Issue by rubyconvict** [collectiveidea/interactor#105]
Could somebody be so kind and take a look at this gem: https://github.com/mindeavor/solid_use_case, this would mean much to me. I wonder, how does it compare to what You are doing, from your perspective. It seems simple (in a good way), ```interactor``` seems too complicated. Maybe I am wrong, looking forward to your opinion. Thanks!

**Comment by laserlemon** [comment]
solid_use_case looks interesting and seems to be attempting to solve the same problem as Interactor is. A use case feels very much like Interactor's concept of an organizer. What I don't like is that each step lives in the use case, which could making reuse of those steps clunkier.

In the end, it looks like a fine library. I'm not in the business of criticizing a gem if it solves your problem. Write your code using both gems and see which you like more. If one of the gems doesn't feel right, consider reporting back. Any library can be improved given thoughtful feedback from a user.

As the author of Interactor, I don't think that it's too complicated. But my opinion's not what's important; it's about _your_ experience with the library. Let me know what you learn.
