### ISSUE TITLE
Parameters validation

### ISSUE THREAD

**Issue by nicolas-besnard** [collectiveidea/interactor#109]
Do you think it can be possible to add parameters validation to this library ?

`context_param :user, presence: true, is_a: 'User`

or even a simpler v1:

`context_params :user, -> (context) {}`

or using some library like [rails_param](https://github.com/nicolasblanco/rails_param) ?

I'll be happy to make a PR for this :)

**Comment by ryansch** [comment]
I just open sourced [metaractor](https://github.com/outstand/metaractor) which does required/optional parameters and some error control (valid/not valid).  It does not do coercion or type checking.

**Comment by philipgiuliani** [comment]
Im using https://github.com/jonstokes/troupe in all of my projects for a long time!

**Comment by adisos** [comment]
```
class RegisterClient
  include Interactor
  include RailsParam::Param

  before :validate_params

  def call
    binding.pry
  end

  def params
    context.params
  end

  def validate_params
    begin
      param! :attribution, String, required: true
    rescue => e
      context.fail!(message: e.message)
    end
  end
end
```

This is what I did. It works fine.

**Comment by berfarah** [comment]
To add to this, I've implemented schema validation for the Interactor::Context - you can see my gem here https://github.com/berfarah/interactor-schema

**Comment by laserlemon** [comment]
Closing in favor of #123.
