### ISSUE TITLE
How to halt execution of the perform without failure?

### ISSUE THREAD

**Issue by zedtux** [collectiveidea/interactor#118]
As of today, in the case I want to halt the execution of the perform for any other reason than a failure, I'm using `context.fail!` (so like a `return` in "normal" Ruby).

Even if this doesn't looks good to me, I was then excepting doing a `context.success!` in order to `return` from my interactor but doesn't work.

All in all, something seems missing to me: Halting an interactor, not because of an error, but because it shouldn't go further.

 - Am I wrong?
 - Should I use something different?
 - Otherwise, could we have something like `context.halt!` or `context.stop!` which will halt the execution and `context.success?` should return `true` in this case.

Thank you in advance.

**Comment by gee-forr** [comment]
I'd like to know the answer to this one myself :)

[Light Service](https://github.com/adomokos/light-service/) has the concept of `context.skip_all!` for ending a series of interactions in an organiser whilst still keeping the status as successful. Would be handy to have that here too.

**Comment by laserlemon** [comment]
Closing in anticipation of [Interactor 4.0](https://github.com/collectiveidea/interactor/projects/1). Please see [this comment](https://github.com/collectiveidea/interactor/pull/122#issuecomment-284411252) for more details.

**Comment by zedtux** [comment]
Thank you @laserlemon for this update 👍

**Comment by mengqing** [comment]
I normally just early return if I want the interactor to halt from proceeding

**Comment by christopherstyles** [comment]
> I normally just early return if I want the interactor to halt from proceeding

@mengqing I’m curious how you do this? Simply returning from the call method doesn’t seem to skip subsequent interactors for me.

**Comment by gee-forr** [comment]
@christopherstyles - @mengqing might just mean he's only using 1 interactor at a time and isn't using organisers?

One thing you could try do in the meantime whilst waiting for interactor 4.0 to land, is to add a flag into the context. Something like `context.skip_rest = true`.

You could then have an `around` block that conditionally executes the interactor based on that value:

```ruby
around do |interactor|
  interactor.call unless interactor.context.skip_rest
end
```

**Comment by christopherstyles** [comment]
Thanks @gee-forr! One quick change to the `unless`, and it works great. Much appreciated 👍 

```ruby
around do |interactor|
  interactor.call unless context.skip
end
