### ISSUE TITLE
Allow interactors to be called with the same options available to the organize method 

### ISSUE THREAD

**Issue by laserlemon** [collectiveidea/interactor#131]
```ruby
MyInteractor.call(some_context, some_options)
```

**Comment by laserlemon** [comment]
Scrapping this idea because most options available within an organizer don't make sense in another context. Passing method names as `:if` and `:unless` options gets confusing quickly because where should those methods be defined? The internals of the interactor don't have access to the instance of the caller to evaluate those methods. I believe it will be better to confine the concept of calling an interactor with options to the scenario of calling those interactors from within an organizer.

**Comment by hedgesky** [comment]
Agree with you.
