### ISSUE TITLE
Error with more than just 'message' param

### ISSUE THREAD

**Issue by jonatasdaniel** [collectiveidea/interactor#141]
I'm trying to handle any errors on my controller, but I want to check which parameter the error is related to. E.G: I want to check all my validations inside my interactor, and return these errors to controllers, and then to my view, then I can specify on my view what error is related to what field.

**Comment by laserlemon** [comment]
We use `message` in the README, but you're free to whatever key, or multiple keys, on the result that you want:

```ruby
def call
  context.user.attributes = context.attributes

  unless context.user.save
    context.fail!(errors: context.user.errors)
  end
end
```

I hope that helps. Thanks for taking the time to share your issue!
