### ISSUE TITLE
Call one Organiser from another

### ISSUE THREAD

**Issue by matt17r** [collectiveidea/interactor#157]
I just tried to set up a hierarchy of Organisers and Interactors but it seems like one Organiser can't call another Organiser. Multiple organize calls in a single Organiser (https://github.com/collectiveidea/interactor/issues/127) is vaguely similar but doesn't let me delegate responsibility to the "sub-Organiser".

Is this a sensible requirement or is calling one Organiser from another a code smell?

A contrived scenario (starting from the README example) is below:
```
class PlaceOrder
  include Interactor::Organizer

  organize CreateOrder, ChargeCard, SendThankYou
end
```

We add a feature for customers to prepay for recurring subscriptions. Each month we need to ship them their order but we don't need to charge their card again:
```
class RepeatSubscriptionOrder
  include Interactor::Organizer

  organize CreateOrder, SendThankYou
end
```

CreateOrder is getting a bit bloated so we want to split it into three Interactors (which apply to both regular and repeat orders); `CheckStockLevels`, `CreateOrder`, `AddMysteryGift`. We could just add both new Interactors to both Organisers but it doesn't feel very DRY. 

If an Organiser could call another Organiser this would be a lot simpler: 
```
class PlaceOrder
  include Interactor::Organizer

  organize ProcessOrder, ChargeCard, SendThankYou
end

class SubscriptionRepeatOrder
  include Interactor::Organizer

  organize ProcessOrder, SendThankYou
end

class ProcessOrder
  include Interactor::Organizer

  organize CheckStockLevels, CreateOrder, AddMysteryGift
end
```

Now any time we make changes to `ProcessOrder` they are inherited by both "parent" Organisers.

**Comment by denispasin** [comment]
I don't see any reason why it should fail. I've done it in the past and it worked quite well.

**Comment by matt17r** [comment]
I just created a brand new project and tested it out. You're absolutely right @denispasin, it does work. I've already deleted the branch I was experimenting with this on so I don't know for sure but I suspect I must have had some other bug in my code (misnamed file or class probably) and just leaped to conclusions.
