### ISSUE TITLE
Add pedestal like interceptors on leave stack  

### ISSUE THREAD

**Issue by laertispappas** [collectiveidea/interactor#162]
Hello,

I was writing an [article](https://medium.com/@laertis.pappas/decoupling-responsibilities-with-pedestal-like-interceptors-in-ruby-part-1-theory-and-background-9f12e83e5cb0) for pedestal [interceptors](http://pedestal.io/reference/interceptors). After a discussion with a colleague of mine he suggested me this gem being similar and I was thinking why `on_leave` callback is missing from the library, if it should be added or not? It would be nice to share your thoughts, experience or any issues / knowledge that would worth sharing.

Thank you.

**Comment by gaffneyc** [comment]
I'm not sure I understand completely but I believe this is covered either by an `after` or `around` hook.
