### ISSUE TITLE
 I want an Organizer that can manage parallel processing.

### ISSUE THREAD

**Issue by yutakakanno** [collectiveidea/interactor#164]
Hello,

I would like to write parallel processing using Interactor.
At that time, I would like to have an Organizer that manages parallel processing like Organizer::Parallel.

Thank you.

**Comment by gaffneyc** [comment]
I'm open to a discussion here but I believe this is out of scope for Interactor. I can imagine enough potential knobs for configuring a [concurrent (not parallel)](https://stackoverflow.com/a/1050257) organizer to an application's needs that I don't think it's general enough to be included.

Fortunately, the API surface for `Interactor::Organizer` is small and it would be easy enough to build a version tailored to your needs.
