### ISSUE TITLE
Call not swallowing exceptions

### ISSUE THREAD

**Issue by TrevorHinesley** [collectiveidea/interactor#166]
Per the documentation:

```
This works because the call class method swallows exceptions.
```

Unless I'm missing something, any errors should be swallowed by `call`, but they're being raised for me unless I manually catch the error inside call and throw it with `fail!`

**Comment by joevandyk** [comment]
Only Interactor::Failure exceptions are automatically caught. Docs could probably be updated to read “these exceptions” to be clearer.
