### ISSUE TITLE
Where should I log for errors?

### ISSUE THREAD

**Issue by alextakitani** [collectiveidea/interactor#177]
I want to log when my Interactor fails, is there a way to do it from inside of the class?

Thanks!

**Comment by john-denisov** [comment]
You can put your errors into context.

**Comment by alextakitani** [comment]
Indeed but that way I have to log the errors on my controller, right?

**Comment by stulzer** [comment]
Not really, you can do it from an interactor.

```ruby
        def call
          ActiveRecord::Base.transaction do
            create_resource
          end
        rescue StandardError => e
          Rails.logger.info "Failed to create resource #{e.message}"
          context.fail!(message: 'Could not create your resource')
        end
```

Another example:

```ruby
        def call
          log_and_fail unless resource.update(params)
        end

        private

        def log_and_fail
          Rails.logger.info "Failed to update resource #{resource.errors.full_messages}"
          context.fail!(message: 'Fail to update resource resource')
        end
```

Is pretty much your call.

if you have an organizer for example I would suggest to log inside the interactors it make sense to log.
There is no right and wrong for it. But on my code I avoid log errors on the controller level.

**Comment by alextakitani** [comment]
Thanks!
