### ISSUE TITLE
good way to use dependency injection when testing interactors?

### ISSUE THREAD

**Issue by tansaku** [collectiveidea/interactor#181]
I have an interactor that reaches out to ruby Mail to send an email.

I was to test the situation where the mail fails to send and I'd usually use dependency injection to pass in a mail class double to simulate the failure ...

I was just wondering if there was a good pattern to use dependency injection for testing interactors, e.g. 

```rb
    class MyEmaiInteractor
      include Interactor
      def call(mail_client = Mail)
        mail_client.deliver do
          from     'me@test.comt'
          to       'you@test.com'
          subject  'Test'
          body     'Some stuff'
        end
      end
```

so that in a test we can pass in a dummy mail client ...

**Comment by sunny** [comment]
You could do dependency injection by doing something like:

```rb
class MyEmailInteractor
  def call
    mail_client.deliver do
      …
    end
  end

  private

  def mail_client
    context.mail_client ||= Mail
  end
end
```

**Comment by timlawrenz** [comment]
@tansaku If this answer is satisfying, could you close the issue?
