### ISSUE TITLE
How know the class name of the interactor that it was executed after returns the context?

### ISSUE THREAD

**Issue by memoxmrdl** [collectiveidea/interactor#182]
For example:

```
> result = PlaceOrder.call
> result.class 
> Interactor::Context # I expect that it returns PlaceOrder but really it's the context
```

**Comment by sunny** [comment]
I don't think it would make sence for it to return `PlaceOrder`, actually. It doesn't return an instance of `PlaceOrder`, it returns the result of calling `PlaceOrder`.

Should you want to know the name of the interactor after calling it you can always do something like:
```rb
interactor = PlaceOrder
interactor.call
interactor.class
# => Interactor::Context
```

**Comment by timlawrenz** [comment]
@memoxmrdl Can this issue be closed?
