### ISSUE TITLE
On success callback for Organizers?

### ISSUE THREAD

**Issue by bradherman** [collectiveidea/interactor#195]
We currently have rollback callbacks for when the stack fails, but it would be nice to also be able to have success callbacks:

`organize CreatePurchase, AuthorizeCard`

If card authorization fails:

```
def rollback
  context.purchase.fail!
end
```

If it succeeds

```
def success
  context.purchase.success!
end
```

It could be accomplished by adding a `MarkSuccess` interactor at the end, but I like the idea of defining callback chains.

**Comment by arthurhess** [comment]
On a side note, @bradherman, one can also use after hooks (which don't run in case the context is failed).

**Comment by bradherman** [comment]
Oh good call @arthurhess ... Not quite as explicit, but adding a helper method to my BaseInteractor would be super easy :+1:
