### ISSUE TITLE
Is the project alive?

### ISSUE THREAD

**Issue by randaalex** [collectiveidea/interactor#199]
It hasn't seen any activity for over a year. Is it still active?

**Comment by Buzzkill-McSquare** [comment]
The latest outstanding PR was posted in May, which suggest that there are at least people _trying_ to contribute. Though the PR wasn't made by an existing contributor, and I don't know who owns the project and where they're at.

**Comment by billgloff** [comment]
Thinking about using https://github.com/sunny/actor instead as it was inspired by Interactor and seems a bit more active.

**Comment by serradura** [comment]
I would like to recommend this project https://github.com/serradura/u-case, the interactor is great and it and other gems gave me the ideas and experience to make my own abstraction to handle business operations.

**Comment by corytheboyd-cirrusmd** [comment]
I'm contemplating just replacing it with our own PORO implementation that actually supports call signatures with keyword arguments. The context API in this gem is just too loose and error prone for sizable production applications

**Comment by cmer** [comment]
Check out https://github.com/adomokos/light-service, it's quite nice.

**Comment by batmanbury** [comment]
Looks like the creator got a job at GitHub...

**Comment by gaffneyc** [comment]
Hey folks 👋 

> It hasn't seen any activity for over a year

And what a year it's been right? Interactor hasn't been a priority this last year as... well... * gestures wildly at everything *

> Is it still active?

Yes, it's still being maintained. There was some work toward a v4 but, as @batmanbury points out, Steve has moved on to other things and he was the driving force behind that work and I haven't had a need to pick it up.

We would love some help maintaining it and moving it forward. I've had a few people reach out this last year offering to help but haven't had the bandwidth until recently to even get that started. So if you'd like to help out let me know and we can start that conversation.

**Comment by alexcameron89** [comment]
@gaffneyc we use this gem quite a bit on my team at work, and I'd love to help improve it. Is addressing general issue tickets or cards in the v4.0 project the best way to help?

**Comment by pboling** [comment]
Another project that was based on this one is https://github.com/jonatasdaniel/interaptor - though I haven't used any of these tools yet, I'm now trying to figure out which one I like best.

**Comment by javierav** [comment]
@gaffneyc What is the status of this project? I would like to help with the maintenance but other developers have previously offered and it seems that this remains stopped.

**Comment by pboling** [comment]
I ended up using https://github.com/sunny/actor, and then wrote a TTY/CLI for it.

**Comment by Buzzkill-McSquare** [comment]
I also switched to using the `actor` gem.

**Comment by javierav** [comment]
Another option is to organize a community and then fork the project maintained by that community... I personally like the simplicity of interactor compared to the other gems available!

**Comment by mainameiz** [comment]
The beauty of this gem is in its simplicity. It has just a few lines of code, but it allows you to make almost everything you want on top of it.
E.g. you want to track `_current_interactor_class `. Not everbody want this feature. But you don't need to wait for the gem maintainer to add this feature into the gem.
You can do it yourself just for your project:

```ruby
module TrackCurrentInteractorClass
  extend ActiveSupport::Concern

  included do
    before do
      context._current_interactor_class = self
    end
  end
end

class Test
  include Interactor
  include TrackCurrentInteractorClass

  def call
    puts "Interactor: #{context._current_interactor_class}"
  end
end
```

Output:
```ruby
> Test.call
Interactor: #<Test:0x000055779a9dc788>
=> #<Interactor::Context _current_interactor_class=#<Test:0x000055779a9dc788 @context=#<Interactor::Context ...>>>
```

Or you want to validate input parameters. I can do it with dry-validation:
```ruby
# Extension for Interactor which adds strictness to the context
#
# @example
#   class Foo
#     include Interactor
#     include Interactor::ContextSchema
#
#     validate_with_schema(
#       Dry::Validation.Schema do
#         required(:name).filled(:str?)
#       end
#     )
#   end
module Interactor
  module ContextSchema
    Error = Class.new(RuntimeError)

    module Validation
      def call(context = {})
        return super(context) unless validation_schema

        validate_context(context)
        super(context)
      end

      def call!(context = {})
        return super(context) unless validation_schema

        validate_context(context)
        super(context)
      end

      private

      # :reek:FeatureEnvy
      def validate_context(context)
        result = validation_schema.call(context.to_h)
        raise Error, result.errors if result.failure?
      end
    end

    def self.included(mod)
      mod.singleton_class.prepend(Validation)
      mod.extend(ClassMethods)
    end

    module ClassMethods
      def validate_with_schema(schema)
        @_validation_schema = schema
      end

      def validation_schema
        @_validation_schema
      end
    end
  end
end
```

**Comment by gaffneyc** [comment]
See https://github.com/collectiveidea/interactor/issues/216#issuecomment-2552571137
