### ISSUE TITLE
A proposal for a non-magical, but stricter context

### ISSUE THREAD

**Issue by brianhempel** [collectiveidea/interactor#67]
In #46 we decided to use an OpenStruct for the context. It removed the magic of creating methods when things were set on the context. It seemed wrong to magically add methods to the interactor based on the calling parameters.

However, now we have problem that every time you want the given email, you have to say `context.email`. This is a break in the syntax-shortening advantage of encapsulation.

What if:

``` ruby
class AuthenticateUser
  include Interactor

  def call
    if user = User.authenticate(context.email, context.password)
      context.user = user
      context.token = user.secret_token
    else
      context.fail!(message: "authenticate_user.failure")
    end
  end
end
```

Instead became:

``` ruby
class AuthenticateUser
  include Interactor

  context_attributes :email, :password
  context_attributes :user, :token
  context_attribute :message

  def call
    if user = User.authenticate(email, password)
      context.user = user
      context.token = user.secret_token
    else
      context.fail!(message: "authenticate_user.failure")
    end
  end
end
```

The context itself is no longer an OpenStruct. Accessing or setting an undeclared attribute on the context will raise `NoMethodError`.

There are several advantages to this approach:
1. Accessing the context in code is easy: `user` instead of `context.user`.
2. It documents what attributes may be used/created on the context.
3. Typos fail fast inside interactors and inside code that calls interactors. `AuthenticateUser.perform(eamil: "alice@example.com")` can explode with an `ArgumentError`.

An organizer would gather all the `context_attribute` of its constituents and pre-populate the context will all the appropriate methods so that the application can call the organizer with arguments needed by any of the interactors.

**Comment by bradstewart** [comment]
I just started using this gem (thanks, it's great), and I really like where this is headed. As a quick and dirty "solution" to some of these issues, I've been using `delegate`--no more typing `context` every time you want to touch something, and it documents what I expect to be on the context. 

E.g. `delegate :user, :email, to: :context`.

**Comment by quidproquo** [comment]
Love the concept behind this gem, though, it would be nice to have context be any type of object. Simply delegate method missing on the context to the passed-in object itself. I feel like forcing the developer to break up parameters into key/value pairs reduces flexibility.

**Comment by mjbellantoni** [comment]
:+1: to this proposal. I've been using this library (thank you! btw) for about a month and I almost immediately added an equivalent to `context_attributes`.  I'm beginning to use organizers and pretty quickly wished something like `requires`/`provides` existed.

**Comment by jonstokes** [comment]
What about something that looks like this:

```
class CreateContact
  include Interactor

  expects :email, :first_name       # these are required, otherwise error
  provides :contact_id              # this may or may not be populated by the interactor
  allows :last_name, :phone_number  # these can be supplied, but if not default is nil

  allows :category do                # this can be supplied, or the proc provides a default
    ContactCategories.default
  end

  allows :country, default: 'USA'     # this can be supplied, default declared inline
end
```

These could just start out as convenience methods, per Steve's suggestion, so that they don't break backwards compatibility.

**Comment by jonstokes** [comment]
FYI, all, if you're following this issue, I'm working on a PR that attempts to address it. You can find it here: https://github.com/collectiveidea/interactor/pull/82

**Comment by greyblake** [comment]
+1 for this proposal!

**Comment by BattleBrisket** [comment]
:+1: Is this still in the cards?

**Comment by andydust** [comment]
👍

**Comment by berfarah** [comment]
Huh... I worked on something like this. Would welcome feedback on the features:
https://github.com/berfarah/interactor-schema

**Comment by jonstokes** [comment]
@berfarah I made a gem for this, as well. Check it out, here: https://github.com/jonstokes/troupe

**Comment by laserlemon** [comment]
Closing for a few reasons:

1. #123 will address explicit inputs.
2. @jonstokes graciously wrote [troupe](https://github.com/jonstokes/troupe).
3. There's no universally agreed-upon behavior for what should happen if what _should_ be provided is _not_ provided.
