### ISSUE TITLE
Question Regarding Behaviour of hooks with a fail!

### ISSUE THREAD

**Issue by hookercookerman** [collectiveidea/interactor#72]
based on the fact that after blocks are only called for successful intereractor calls; should rolback be given the same dsl love? (failure) or should we be explicit on the callback naming here; cos what we are saying is after_success.

just a thought

also prehaps I want to be able to define more then 1 rollback the same as I can with an after hook

**Comment by mjbellantoni** [comment]
:+1: To `after_failure`. In my use case, I'm trying to send observers a message that the action failed.  I can do this manually in a plain old `Interactor` but not with an `Organizer` (unless I monkey patch.)
