### ISSUE TITLE
Testing Interactors example from README fails (raises Interactor::Failure)

### ISSUE THREAD

**Issue by kulte** [collectiveidea/interactor#75]

**Comment by emilford** [comment]
@thebucknerlife 

Are you able to post the code you're wanting to test? RSpec's [`raise_error`](https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/raise-error-matcher) expectation matcher to assert the expected failure is probably what you're after.

**Comment by thebucknerlife** [comment]
Unfortunately I couldn't get that far because Interactor::Failure wouldn't be caught by raise_error. I was able to figure it out and refactor my tests based on the above. This should definitely be addressed in the Readme, though :/

**Comment by emilford** [comment]
@thebucknerlife 

The whole point of `raise_error` is to catch the exception raised in your test.  If you call the interactor inside the `expect` block of the `raise_error` it will catch the exception.  We can certainly add a more realistic example to the README.  For now here's a super contrived example:

```
class RaiseException
  include Interactor

  def call
    context.fail!
  end
end
```

```
require "spec_helper"

describe RaiseException do
  it "raises an exception" do
    expect { RaiseException.call! }.to raise_exception(Interactor::Failure)
  end
end
```

**Comment by thebucknerlife** [comment]
Thanks @emilford
